version: '2'

services:
    elasticsearch:
      build: elasticsearch/
      environment:
        # This helps ES out with memory usage
        - ES_JAVA_OPTS=-Xmx1g -Xms1g
      volumes:
        # Persist elasticsearch data to a volume
        - elasticsearch:/usr/share/elasticsearch/data
        # Extra ES configuration options
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - elk

    logstash:
      build: logstash/
      environment:
        # This helps Logstash out if it gets too busy
        - LS_HEAP_SIZE=2048m
      volumes:
        # volume mount the logstash config
        - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      ports:
        # UDP port for syslogs
        - "5000:5000/udp"
        # Default TCP port
        - "5001:5001"
      networks:
        - elk
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

    kibana:
      build: kibana/
      environment:
        # Point Kibana to the elasticsearch container
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - "5601:5601"
      networks:
        - elk
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

networks:
    elk:
        driver: bridge
    
volumes:
    elasticsearch: /usr/share/elasticsearch/data